# Distribución límite (Caso II)

Supongamos que tenemos la siguiente matriz de transición

$$\textbf{P} =
\begin{pmatrix}
\frac{1}{2}  & \frac{1}{2}  &  0            &  0\\
       0     & \frac{1}{2}  &  \frac{1}{2}  &  0 \\
       0     &        0     & \frac{1}{2}   &  \frac{1}{2} \\
       0     &        0     &       0       & \frac{1}{2} 
\end{pmatrix}$$

Obtener $\lim_{n \rightarrow \infty} P_{i,j}^n$.

In [2]:
# Función para calcular la potencia de una matriz
mat.pow <- function(m, n){
  # inputs:
  #   m : matriz 
  #   n : potencia
  # outputs:
  #   Mn : matriz potencia n
  for(i in 1:n){
    if(i == 1){
      Mn <- m
    }else{
      Mn <- Mn%*%m
    }
  }
  return(Mn)
}

Probamos para $n$ de $1$ hasta $50$.

In [5]:
# Declaranmos nuestra matriz
P = matrix(c(1/2, 1/2, 0, 0, 
             0, 1/2, 1/2, 0,
             0, 0 , 1/2, 1/2,
             0, 0, 0, 1/2), ncol=4, byrow = TRUE)
print(P)

     [,1] [,2] [,3] [,4]
[1,]  0.5  0.5  0.0  0.0
[2,]  0.0  0.5  0.5  0.0
[3,]  0.0  0.0  0.5  0.5
[4,]  0.0  0.0  0.0  0.5


In [6]:
n.max = 50
for(i in 1:n.max){
    Pn <- mat.pow(P, n=i)
    cat(paste('Matriz de probabilidades de transición a n= ', i, ' pasos \n', sep=''))
    print(Pn)
}

Matriz de probabilidades de transición a n= 1 pasos 
     [,1] [,2] [,3] [,4]
[1,]  0.5  0.5  0.0  0.0
[2,]  0.0  0.5  0.5  0.0
[3,]  0.0  0.0  0.5  0.5
[4,]  0.0  0.0  0.0  0.5
Matriz de probabilidades de transición a n= 2 pasos 
     [,1] [,2] [,3] [,4]
[1,] 0.25 0.50 0.25 0.00
[2,] 0.00 0.25 0.50 0.25
[3,] 0.00 0.00 0.25 0.50
[4,] 0.00 0.00 0.00 0.25
Matriz de probabilidades de transición a n= 3 pasos 
      [,1]  [,2]  [,3]  [,4]
[1,] 0.125 0.375 0.375 0.125
[2,] 0.000 0.125 0.375 0.375
[3,] 0.000 0.000 0.125 0.375
[4,] 0.000 0.000 0.000 0.125
Matriz de probabilidades de transición a n= 4 pasos 
       [,1]   [,2]   [,3]   [,4]
[1,] 0.0625 0.2500 0.3750 0.2500
[2,] 0.0000 0.0625 0.2500 0.3750
[3,] 0.0000 0.0000 0.0625 0.2500
[4,] 0.0000 0.0000 0.0000 0.0625
Matriz de probabilidades de transición a n= 5 pasos 
        [,1]    [,2]    [,3]    [,4]
[1,] 0.03125 0.15625 0.31250 0.31250
[2,] 0.00000 0.03125 0.15625 0.31250
[3,] 0.00000 0.00000 0.03125 0.15625
[4,] 0.00000 0.00000 0.0000

In [9]:
# suma de los elementos del estado i=0
sum(Pn[1,])

[1] 1.854161e-11